{"uuid":"0bc80dec-d430-49ce-b164-b6ee9c5e2ba4","historyId":"6798437cbc593c792dea415f26ec39c7","fullName":"org.br.curso.tests.DBTests.testInsercao","labels":[{"name":"package","value":"org.br.curso.tests.DBTests"},{"name":"testClass","value":"org.br.curso.tests.DBTests"},{"name":"testMethod","value":"testInsercao"},{"name":"parentSuite","value":"Default suite"},{"name":"suite","value":"Default test"},{"name":"subSuite","value":"org.br.curso.tests.DBTests"},{"name":"host","value":"LP0948"},{"name":"thread","value":"13364@LP0948.main(1)"}],"links":[],"name":"testInsercao","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Error on test.","trace":"java.lang.AssertionError: Error on test.\r\n\tat org.testng.Assert.fail(Assert.java:85)\r\n\tat org.br.curso.tests.DBTests.testInsercao(DBTests.java:26)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)\r\n\tat java.lang.reflect.Method.invoke(Unknown Source)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)\r\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:583)\r\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)\r\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:648)\r\n\tat org.testng.TestRunner.run(TestRunner.java:505)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:455)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:364)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1137)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1049)\r\n\tat org.testng.TestNG.run(TestNG.java:1017)\r\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)\r\nCaused by: java.util.concurrent.ExecutionException: java.lang.reflect.InvocationTargetException\r\n\tat com.br.inmetrics.frm.bdd.Gherkin.executeScenario_(Gherkin.java:304)\r\n\tat org.br.curso.tests.DBTests.testInsercao(DBTests.java:24)\r\n\t... 25 more\r\nCaused by: java.lang.reflect.InvocationTargetException\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)\r\n\tat java.lang.reflect.Method.invoke(Unknown Source)\r\n\tat com.br.inmetrics.frm.helpers.GherkinHelper.invokeScenario(GherkinHelper.java:209)\r\n\tat com.br.inmetrics.frm.bdd.Gherkin.executeScenario_(Gherkin.java:293)\r\n\t... 26 more\r\nCaused by: java.util.concurrent.ExecutionException: java.lang.reflect.InvocationTargetException\r\n\tat com.br.inmetrics.frm.bdd.Gherkin.execute_(Gherkin.java:180)\r\n\tat org.br.curso.features.DBFeature.validarInsercaoClienteBase(DBFeature.java:20)\r\n\t... 32 more\r\nCaused by: java.lang.reflect.InvocationTargetException\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)\r\n\tat java.lang.reflect.Method.invoke(Unknown Source)\r\n\tat com.br.inmetrics.frm.bdd.Gherkin.executeStep_(Gherkin.java:214)\r\n\tat com.br.inmetrics.frm.bdd.Gherkin.execute_(Gherkin.java:174)\r\n\t... 33 more\r\nCaused by: java.lang.AssertionError: Erro na inserção do cliente\r\n\tat org.testng.Assert.fail(Assert.java:85)\r\n\tat org.br.curso.steps.DBSteps.dado_que_faca_a_insercao_de_um_novo_cliente(DBSteps.java:23)\r\n\t... 39 more\r\nCaused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: Customers)\r\n\tat org.sqlite.core.DB.newSQLException(DB.java:941)\r\n\tat org.sqlite.core.DB.newSQLException(DB.java:953)\r\n\tat org.sqlite.core.DB.throwex(DB.java:918)\r\n\tat org.sqlite.core.NativeDB.prepare_utf8(Native Method)\r\n\tat org.sqlite.core.NativeDB.prepare(NativeDB.java:134)\r\n\tat org.sqlite.core.DB.prepare(DB.java:257)\r\n\tat org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:47)\r\n\tat org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)\r\n\tat org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)\r\n\tat org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)\r\n\tat org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)\r\n\tat org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)\r\n\tat org.br.curso.actions.DBActions.insertCustomer(DBActions.java:133)\r\n\tat org.br.curso.steps.DBSteps.dado_que_faca_a_insercao_de_um_novo_cliente(DBSteps.java:21)\r\n\t... 39 more\r\n"},"stage":"finished","start":1560182845709,"stop":1560182846279,"steps":[{"name":"Dado que faça a inserção de um novo cliente","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"java.lang.reflect.InvocationTargetException","trace":"java.lang.reflect.InvocationTargetException\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)\r\n\tat java.lang.reflect.Method.invoke(Unknown Source)\r\n\tat com.br.inmetrics.frm.bdd.Gherkin.executeStep_(Gherkin.java:214)\r\n\tat com.br.inmetrics.frm.bdd.Gherkin.execute_(Gherkin.java:174)\r\n\tat org.br.curso.features.DBFeature.validarInsercaoClienteBase(DBFeature.java:20)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)\r\n\tat java.lang.reflect.Method.invoke(Unknown Source)\r\n\tat com.br.inmetrics.frm.helpers.GherkinHelper.invokeScenario(GherkinHelper.java:209)\r\n\tat com.br.inmetrics.frm.bdd.Gherkin.executeScenario_(Gherkin.java:293)\r\n\tat org.br.curso.tests.DBTests.testInsercao(DBTests.java:24)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)\r\n\tat java.lang.reflect.Method.invoke(Unknown Source)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)\r\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:583)\r\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)\r\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:648)\r\n\tat org.testng.TestRunner.run(TestRunner.java:505)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:455)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:364)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1137)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1049)\r\n\tat org.testng.TestNG.run(TestNG.java:1017)\r\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)\r\nCaused by: java.lang.AssertionError: Erro na inserção do cliente\r\n\tat org.testng.Assert.fail(Assert.java:85)\r\n\tat org.br.curso.steps.DBSteps.dado_que_faca_a_insercao_de_um_novo_cliente(DBSteps.java:23)\r\n\t... 39 more\r\nCaused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: Customers)\r\n\tat org.sqlite.core.DB.newSQLException(DB.java:941)\r\n\tat org.sqlite.core.DB.newSQLException(DB.java:953)\r\n\tat org.sqlite.core.DB.throwex(DB.java:918)\r\n\tat org.sqlite.core.NativeDB.prepare_utf8(Native Method)\r\n\tat org.sqlite.core.NativeDB.prepare(NativeDB.java:134)\r\n\tat org.sqlite.core.DB.prepare(DB.java:257)\r\n\tat org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:47)\r\n\tat org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)\r\n\tat org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)\r\n\tat org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)\r\n\tat org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)\r\n\tat org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)\r\n\tat org.br.curso.actions.DBActions.insertCustomer(DBActions.java:133)\r\n\tat org.br.curso.steps.DBSteps.dado_que_faca_a_insercao_de_um_novo_cliente(DBSteps.java:21)\r\n\t... 39 more\r\n"},"stage":"finished","start":1560182845744,"stop":1560182846255},{"name":"Exception on scenario execution","status":"failed","stage":"finished","start":1560182846255,"stop":1560182846255}],"parameters":[]}